services:
  lanchoneteapi:
    image: brunodiego5/fiap.tc.fase1:latest
    ports:
      - "80:80"
    restart: always
    environment:
      - MongoDBConnection__Server=mongodb://mongo:27017/lanchoneteDB
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: